name: CI

on:
  pull_request:

env:
  NX_DAEMON: false

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: 'npm'

      - run: npm ci
      - run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH
      - run: nx run-many --verbose -t build

      - uses: actions/cache/save@v4
        with:
          path: .nx/cache
          key: nx-${{ github.sha }}

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: 'npm'

      - run: npm ci
      - run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - uses: actions/cache/restore@v4
        with:
          path: .nx/cache
          key: nx-${{ github.sha }}

      - run: nx run-many --verbose -t lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: 'npm'

      - run: npm ci
      - run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - uses: actions/cache/restore@v4
        with:
          path: .nx/cache
          key: nx-${{ github.sha }}

      - run: nx run-many --verbose -t test